import React, { useState, useEffect } from 'react'
import BaseCard from '../components/BaseCard'

/**
 * Base page element for non-users. Displays a container filled with records
 * as cards for every released pokemon that's retrieved from the API. Each card
 * is generated by taking the pokemon and displaying images/buttons if each
 * category is set in the pokemon's data.
 *
 * @returns page element for a non-user
 */
const BasePokemonPage = () => {
  //state for pokemon data
  let [pokemonList, setPokemonList] = useState([]);
  //state for how many generations of pokemon there are
  //used for the page separators
  let [genList, setGenList] = useState([]);

  useEffect(() => {
    getPokemonDataFromAPI();
  }, [])

  /**
   * Sends request to API for a list of all pokemon in the database. Upon receiving
   * a valid response, sets the received data to the pokemonList state and generates
   * the generation list.
   */
  let getPokemonDataFromAPI = async() => {
    let response = await fetch('http://127.0.0.1:8000/api/pokemon-list', {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
        }
    })
    let data = await response.json();
    if(response.status === 200){
      setPokemonList(data);
    }
    else {
      alert("Error retrieving pokemon list from server.")
      return;
    }
    let numGens = data.at(-1).generation;
    let newGenList = [];
    for(let i = 1; i <= numGens; i++) {
      newGenList.push(i);
    }
    setGenList(newGenList);
  }

  return(
    <div className="container">
    {
      genList.map((gen, index) => {
        return(
          <div key={index} className="genContainer">
            <h1 className="genHeader">
              Generation {gen}
            </h1>
            <div className="pokemonContainer">
              {pokemonList.map((pokemon, index2) => {
                if(pokemon.generation === gen){
                  return(
                    <BaseCard key={index2} pokemon={pokemon} />
                  )
                }
                else{return null;}
              })}
            </div>
          </div>
        )
      })
    }
    </div>
  )
}

export default BasePokemonPage;
